[postgres]
dsn = "postgresql://USER:PASSWORD@HOST:5432/DBNAME?sslmode=require"
participation_table = "participation"
play_by_play_data_table = "play_by_play_data"
epa_table = "epa"
weekly_rosters_table = "weekly_rosters"
pp_data_table = "pp_data"

[data_urls]
participation.csv = "https://<your-storage>/participation.csv"
play_by_play_data.csv = "https://<your-storage>/play_by_play_data.csv"
epa.csv = "https://<your-storage>/epa.csv"
weekly_rosters.csv = "https://<your-storage>/weekly_rosters.csv"
pp_data.csv = "https://<your-storage>/pp_data.csv"
